FROM debian:stable-slim

ARG BUNDLE_DIR

RUN apt-get update -y \
  && apt-get install curl apt-transport-https lsb-release gnupg -y \
  && curl -sL https://aka.ms/InstallAzureCLIDeb | bash \
  && apt-get update \
  && apt-get install azure-cli

COPY . ${BUNDLE_DIR}
