FROM debian:stable-slim

ARG BUNDLE_DIR

# Install jq, we aren't using the mixin because it's an example bundle and jq
# isn't a default mixin
RUN apt-get update && apt-get install gnupg2 jq -y && rm -rf /var/lib/apt/lists/*

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . ${BUNDLE_DIR}
